#!/usr/bin/python

import sys
import gettext

import gtk
import dbus
import webkit
import gobject

import dbus
import dbus.service
import dbus.mainloop.glib

gobject.threads_init()
dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
dbus.mainloop.glib.threads_init()

gettext.install('pagico', unicode=True)

ui_info = '''
<ui>
  <menubar name='MenuBar'>
      <menu action='FileMenu'>
          <menu action='NewMenu'>
              <menuitem action='NewTaskItem'/>
              <separator/>
              <menuitem action='NewProjectItem'/>
              <menuitem action='ContactItem'/>
          </menu>
          <separator/>
          <menuitem action='DashboardItem'/>
          <separator/>
          <menuitem action='InboxItem'/>
          <menuitem action='ProjectsItem'/>
          <menuitem action='ContactsItem'/>
          <menuitem action='WorkspaceItem'/>
          <separator/>
          <menuitem action='LockDatabaseItem'/>
          <menuitem action='CreateNewDatabaseItem'/>
          <separator/>
          <menuitem action='QuitPagicoItem'/>
          <menuitem action='CloseDatabaseItem'/>
      </menu>
      <menu action='EditMenu'>
          <menuitem action='CutItem'/>
          <menuitem action='CopyItem'/>
          <menuitem action='PasteItem'/>
          <separator/>
          <menuitem action='SnapbackItem'/>
          <menuitem action='PrintItem'/>
      </menu>
      <menu action='ToolsMenu'>
          <menuitem action='ProgramPreferencesItem'/>
          <menuitem action='DatabasePreferencesItem'/>
      </menu>
      <menu action='HelpMenu'>
          <menuitem action='UserManualItem'/>
          <menuitem action='OnlineHelpItem'/>
          <separator/>
          <menuitem action='WebsiteItem'/>
          <menuitem action='CheckupdateItem'/>
          <menuitem action='AboutItem'/>
      </menu>
  </menubar>
</ui>
'''

class WebView(webkit.WebView):
    def __init__(self):
        webkit.WebView.__init__(self)


class Pagico(gtk.Window):

    def __init__(self):
        gtk.Window.__init__(self)

        self.set_title('Pagico')
        self.set_size_request(1024, 600)
        vbox = gtk.VBox(False, 0)
        self.add(vbox)

        bus = dbus.SessionBus()
        try:
            object = bus.get_object("com.pagico.clienty", "/com/pagico/clienty", 'com.pagico.clienty')
            bus.add_signal_receiver(self.on_db_signal_received, interface_keyword='dbus_interface', member_keyword='db')
        except Exception, e:
            print e

        merge = gtk.UIManager()
        self.set_data("ui-manager", merge)
        merge.insert_action_group(self._create_action_group(), 0)
        self.add_accel_group(merge.get_accel_group())

        try:
            mergeid = merge.add_ui_from_string(ui_info)
        except gobject.GError, msg:
            print "building menus failed: %s" % msg

        bar = merge.get_widget("/MenuBar")
        bar.show() 
        vbox.pack_start(bar, False, False, 0)

        self.webview = WebView()
        vbox.pack_start(self.webview, True, True, 0)

        self.webview.connect('notify::load-status', self.on_load_status_changed)
        self.connect('destroy', lambda f: gtk.main_quit())

        self.webview.load_uri('http://127.0.0.1:1200/?nopopup')

        self.show_all()

    def catchall_signal_handler(self, *args, **kwargs):
        print ("Caught signal (in catchall handler) "
                           + kwargs['dbus_interface'] + "." + kwargs['member'])
        for arg in args:
            print "        " + str(arg)

    def activate_action(self):
        pass

    def on_load_status_changed(self, widget, status):
        print widget, widget.get_load_status().value_nick

    def _create_action_group(self):
        entries = (
            ("FileMenu", None, _("_File")),
            ("NewMenu", None, _("_New")),
            ("NewTaskItem", None, _("Task"), "<control>T",
             None, self.activate_action),
            ("NewProjectItem", None, _("Project"), "<control>N",
             None, self.activate_action),
            ('NewContactProfileItem', None, _('Contact Profile'),
             '<control>M', None, self.activate_action),
            ('DashboardItem', None, _('Dashboard'),
             '<control>1', None, self.activate_action),
            ('InboxItem', None, _('Inbox'),
             '<control>2', None, self.activate_action),
            ('ProjectsItem', None, _('Projects'),
             '<control>3', None, self.activate_action),
            ('ContactsItem', None, _('Contacts'),
             '<control>4', None, self.activate_action),
            ('WorkspaceItem', None, _('Workspace'),
             '<control>5', None, self.activate_action),
            ('LockDatabaseItem', None, _('Lock Database'),
             '<control>L', None, self.activate_action),
            ('CloseDatabaseItem', None, _('Close Database'),
             '<shift><control>W', None, self.activate_action),
            ('CreateNewDatabaseItem', None, _('Create New Database'),
             '<shift><control>N', None, self.activate_action),
            ('EditMenu', None, _('_Edit')),
            ('CutItem', None, _('Cu_t'),
             '<control>X', None, self.activate_action),
            ('CopyItem', None, _('_Copy'),
             '<control>C', None, self.activate_action),
            ('PasteItem', None, _('_Paste'),
             '<control>V', None, self.activate_action),
            ('SnapbackItem', None, _('_Snapback'),
             '<control>left', None, self.activate_action),
            ('PrintItem', None, _('Print'),
             None, None, self.activate_action),
          )

        # Create the menubar and toolbar
        action_group = gtk.ActionGroup("AppWindowActions")
        action_group.add_actions(entries)

        return action_group


class PagicoClient(dbus.service.Object):
    def __init__(self, session_bus, window):
        bus_name = dbus.service.BusName('com.pagico.clienty', bus=session_bus)
        dbus.service.Object.__init__(self, bus_name, '/com/pagico/clienty')

        self.window = window

    def run(self):
        gtk.main()

    @dbus.service.method(dbus_interface='com.pagico.clienty')
    def show_window(self):
        self.window.present()

    @dbus.service.method(dbus_interface='com.pagico.clienty')
    def opendb(self):
        print 'try to open db'

    @dbus.service.method(dbus_interface='com.pagico.clienty')
    def createdb(self):
        print 'try to create db'

    @dbus.service.method(dbus_interface='com.pagico.clienty')
    def launch(self, path):
        print 'try to launch path', path


if __name__ == '__main__':
    session_bus = dbus.SessionBus()

    if session_bus.request_name('com.pagico.clienty') != \
            dbus.bus.REQUEST_NAME_REPLY_PRIMARY_OWNER:
        method = session_bus.get_object('com.pagico.clienty',
                                        '/com/pagico/clienty')\
                                                .get_dbus_method("show_window")
        method()
        sys.exit(1)
    else:
        window = Pagico()
        client = PagicoClient(session_bus, window)
        client.run()
