#!/usr/bin/python

import sys
import dbus
import dbus.service
import dbus.mainloop.glib

if __name__ == '__main__':
    session_bus = dbus.SessionBus()

    if len(sys.argv) < 2:
        print('Usage: %s --[opendb][createdb][launch] [file]' % sys.argv[0])
        sys.exit(1)

    if session_bus.request_name('com.pagico.clienty') != \
            dbus.bus.REQUEST_NAME_REPLY_PRIMARY_OWNER:
        method_name = sys.argv[1]
        method_name = method_name.strip('-')

        if method_name == 'launch':
            if len(sys.argv) == 3:
                filename = sys.argv[2]
            else:
                print('Usage: %s --launch [file]' % sys.argv[0])
                sys.exit(1)
        else:
            filename = ''

        method = session_bus.get_object('com.pagico.clienty',
                                        '/com/pagico/clienty')\
                                                .get_dbus_method(method_name)
        if filename:
            method(filename)
        else:
            method()

        sys.exit(0)
    else:
        print('Can not own the com.pagico.clienty')
        sys.exit(1)
