#!/usr/bin/python

import os
import sys
import time
import shutil
import gettext
import subprocess

import gtk
import glib
import dbus
import webkit
import gobject

import dbus
import dbus.service
import dbus.mainloop.glib

gobject.threads_init()
dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)
dbus.mainloop.glib.threads_init()

gettext.install('pagico', unicode=True)

ui_info = '''
<ui>
  <menubar name='MenuBar'>
      <menu action='FileMenu'>
          <menu action='NewMenu'>
              <menuitem action='NewTaskItem'/>
              <separator/>
              <menuitem action='NewProjectItem'/>
              <menuitem action='ContactItem'/>
          </menu>
          <separator/>
          <menuitem action='DashboardItem'/>
          <separator/>
          <menuitem action='InboxItem'/>
          <menuitem action='ProjectsItem'/>
          <menuitem action='ContactsItem'/>
          <menuitem action='WorkspaceItem'/>
          <separator/>
          <menuitem action='LockDatabaseItem'/>
          <menuitem action='CreateNewDatabaseItem'/>
          <separator/>
          <menuitem action='QuitPagicoItem'/>
          <menuitem action='CloseDatabaseItem'/>
      </menu>
      <menu action='EditMenu'>
          <menuitem action='CutItem'/>
          <menuitem action='CopyItem'/>
          <menuitem action='PasteItem'/>
          <separator/>
          <menuitem action='SnapbackItem'/>
          <menuitem action='PrintItem'/>
      </menu>
      <menu action='ToolsMenu'>
          <menuitem action='ProgramPreferencesItem'/>
          <menuitem action='DatabasePreferencesItem'/>
      </menu>
      <menu action='HelpMenu'>
          <menuitem action='UserManualItem'/>
          <menuitem action='OnlineHelpItem'/>
          <separator/>
          <menuitem action='WebsiteItem'/>
          <menuitem action='CheckupdateItem'/>
          <menuitem action='AboutItem'/>
      </menu>
  </menubar>
</ui>
'''

class WebView(webkit.WebView):
    def __init__(self):
        webkit.WebView.__init__(self)


class Pagico(gtk.Window):
    TARGET = [
        ('STRING', 0, 0),
        ('text/plain', 0, 0),
    ]

    CONFIG_PATH = os.path.join(glib.get_user_config_dir(), 'pagico')
    if not os.path.exists(CONFIG_PATH):
        os.makedirs(CONFIG_PATH)


    def __init__(self):
        gtk.Window.__init__(self)

        self.init_daemon()
        self.load_config()
        self.start_abyssws()

        self.set_title('Pagico')
        self.set_size_request(1024, 600)
        vbox = gtk.VBox(False, 0)
        self.add(vbox)

        bus = dbus.SessionBus()
        try:
            object = bus.get_object("com.pagico.clienty", "/com/pagico/clienty", 'com.pagico.clienty')
            bus.add_signal_receiver(self.on_db_signal_received, interface_keyword='dbus_interface', member_keyword='db')
        except Exception, e:
            print e

        merge = gtk.UIManager()
        self.set_data("ui-manager", merge)
        merge.insert_action_group(self._create_action_group(), 0)
        self.add_accel_group(merge.get_accel_group())

        try:
            mergeid = merge.add_ui_from_string(ui_info)
        except gobject.GError, msg:
            print "building menus failed: %s" % msg

        bar = merge.get_widget("/MenuBar")
        bar.show() 
        vbox.pack_start(bar, False, False, 0)

        self.webview = WebView()
        self.webview.drag_dest_set(gtk.DEST_DEFAULT_ALL, self.TARGET[:-1],
                                   gtk.gdk.ACTION_COPY | gtk.gdk.ACTION_MOVE | gtk.gdk.ACTION_LINK)
        self.webview.connect('drag-data-received', self.on_drag_data_received)

        vbox.pack_start(self.webview, True, True, 0)

        self.webview.connect('notify::load-status', self.on_load_status_changed)
        self.webview.connect('notify::title', self.on_title_changed)
        self.connect('destroy', self.on_destroy)

        self.webview.load_uri('http://127.0.0.1:1200/?nopopup')

        self.show_all()

    def on_destroy(self, widget):
        self.end_abyssws()
        self.unload_config()
        self.quit_daemon()
        gtk.main_quit()

    def init_daemon(self):
        try:
            systembus = dbus.SystemBus()
            self.daemon = systembus.get_object('com.pagico.daemon', '/com/pagico/daemon')
        except Exception, e:
            self.daemon = None

    def load_config(self):
        abyss_config_path = os.path.join(self.CONFIG_PATH, 'abyss.conf')
        abyss_log_path = os.path.join(self.CONFIG_PATH, 'log')

        if not os.path.exists(abyss_config_path):
            shutil.copy('/opt/pagico/CodeX/extras/httpd_linux.txt', abyss_config_path)
        if not os.path.exists(abyss_log_path):
            os.makedirs(abyss_log_path)

        method = self.daemon.get_dbus_method('load_config', dbus_interface='com.pagico.daemon')
        method(self.CONFIG_PATH)

    def start_abyssws(self):
        subprocess.Popen('/opt/pagico/httpd/abyssws')
        time.sleep(2)

    def end_abyssws(self):
        os.system('killall -KILL abyssws')
        os.system('killall -KILL php-cgi')

    def unload_config(self):
        method = self.daemon.get_dbus_method('unload_config', dbus_interface='com.pagico.daemon')
        method()

    def quit_daemon(self):
        method = self.daemon.get_dbus_method('exit', dbus_interface='com.pagico.daemon')
        method()

    def on_drag_data_received(self, widget, drag_context, x, y, selection_data, info, timestamp):
        print drag_context, selection_data, info, timestamp

    def catchall_signal_handler(self, *args, **kwargs):
        print ("Caught signal (in catchall handler) "
                           + kwargs['dbus_interface'] + "." + kwargs['member'])
        for arg in args:
            print "        " + str(arg)

    def activate_action(self):
        pass

    def on_load_status_changed(self, widget, status):
        print widget, widget.get_load_status().value_nick

    def on_title_changed(self, widget, param):
        title = widget.get_property('title')
        if title:
            self.set_title(title)

    def create_new_database(self):
        dialog = gtk.FileChooserDialog(title=_('Create new database'),
                                       parent=self,
                                       action=gtk.FILE_CHOOSER_ACTION_CREATE_FOLDER,
                                       buttons=(gtk.STOCK_CANCEL, gtk.RESPONSE_REJECT,
                                                gtk.STOCK_SAVE, gtk.RESPONSE_ACCEPT))
        response = dialog.run()
        filename = dialog.get_filename()
        dialog.destroy()

        if response ==  gtk.RESPONSE_ACCEPT:
            if not filename.endswith('.pgco'):
                pgco_filename = filename + '.pgco'
                if not os.path.exists(filename):
                    os.unlink(filename)
                    os.mkdir(pgco_filename)
                else:
                    pass
            else:
                if not os.path.exists(filename):
                    os.mkdir(filename)
                else:
                    pass

            f = open(os.path.join(self.CONFIG_PATH, 'DB_to_create'), 'w')
            f.write(filename)
            f.close()

            self.webview.load_uri('http://127.0.0.1:1200/start/loader.php')

    def open_database(self):
        dialog = gtk.FileChooserDialog(title=_('Open database'),
                                       parent=self,
                                       action=gtk.FILE_CHOOSER_ACTION_SELECT_FOLDER,
                                       buttons=(gtk.STOCK_CANCEL, gtk.RESPONSE_REJECT,
                                                gtk.STOCK_OPEN, gtk.RESPONSE_ACCEPT))
        response = dialog.run()
        filename = dialog.get_filename()
        dialog.destroy()

        if response == gtk.RESPONSE_ACCEPT:
            f = open(os.path.join(self.CONFIG_PATH, 'DB_to_load'), 'w')
            f.write(filename)
            f.close()

            self.webview.load_uri('http://127.0.0.1:1200/start/loader.php')

    def _create_action_group(self):
        entries = (
            ("FileMenu", None, _("_File")),
            ("NewMenu", None, _("_New")),
            ("NewTaskItem", None, _("Task"), "<control>T",
             None, self.activate_action),
            ("NewProjectItem", None, _("Project"), "<control>N",
             None, self.activate_action),
            ('NewContactProfileItem', None, _('Contact Profile'),
             '<control>M', None, self.activate_action),
            ('DashboardItem', None, _('Dashboard'),
             '<control>1', None, self.activate_action),
            ('InboxItem', None, _('Inbox'),
             '<control>2', None, self.activate_action),
            ('ProjectsItem', None, _('Projects'),
             '<control>3', None, self.activate_action),
            ('ContactsItem', None, _('Contacts'),
             '<control>4', None, self.activate_action),
            ('WorkspaceItem', None, _('Workspace'),
             '<control>5', None, self.activate_action),
            ('LockDatabaseItem', None, _('Lock Database'),
             '<control>L', None, self.activate_action),
            ('CloseDatabaseItem', None, _('Close Database'),
             '<shift><control>W', None, self.activate_action),
            ('CreateNewDatabaseItem', None, _('Create New Database'),
             '<shift><control>N', None, self.activate_action),
            ('EditMenu', None, _('_Edit')),
            ('CutItem', None, _('Cu_t'),
             '<control>X', None, self.activate_action),
            ('CopyItem', None, _('_Copy'),
             '<control>C', None, self.activate_action),
            ('PasteItem', None, _('_Paste'),
             '<control>V', None, self.activate_action),
            ('SnapbackItem', None, _('_Snapback'),
             '<control>left', None, self.activate_action),
            ('PrintItem', None, _('Print'),
             None, None, self.activate_action),
            ('ToolsMenu', None, _('_Tools')),
            ('ProgramPreferencesItem', None, _('Program Preferences')),
            ('DatabasePreferencesItem', None, _('Database Preferences')),
            ('HelpMenu', None, _('_Help')),
            ('UserManualItem', None, _('_User Manual')),
            ('OnlineHelpItem', None, _('_Online Interactive Help')),
            ('WebsiteItem', None, _('Pagico _Website')),
            ('CheckupdateItem', None, _('Check for U_pdate')),
            ('AboutItem', None, _('_About ...')),
          )

        # Create the menubar and toolbar
        action_group = gtk.ActionGroup("AppWindowActions")
        action_group.add_actions(entries)

        return action_group


class PagicoClient(dbus.service.Object):
    def __init__(self, session_bus, window):
        bus_name = dbus.service.BusName('com.pagico.clienty', bus=session_bus)
        dbus.service.Object.__init__(self, bus_name, '/com/pagico/clienty')

        self.window = window

    def run(self):
        gtk.main()

    @dbus.service.method(dbus_interface='com.pagico.clienty')
    def show_window(self):
        self.window.present()

    @dbus.service.method(dbus_interface='com.pagico.clienty')
    def opendb(self):
        print 'try to open db'
        self.window.open_database()

    @dbus.service.method(dbus_interface='com.pagico.clienty')
    def createdb(self):
        print 'try to create db'
        self.window.create_new_database()

    @dbus.service.method(dbus_interface='com.pagico.clienty')
    def launch(self, path):
        print 'try to launch path', path


def show_splash():
    win = gtk.Window(gtk.WINDOW_POPUP)
    win.set_position(gtk.WIN_POS_CENTER)

    vbox = gtk.VBox(False, 0)
    image = gtk.Image()
    image.set_from_file('/opt/pagico/splash.png')

    vbox.pack_start(image)
    win.add(vbox)

    win.show_all()

    while gtk.events_pending():
        gtk.main_iteration()

    win.destroy()


if __name__ == '__main__':
    show_splash()

    session_bus = dbus.SessionBus()

    if session_bus.request_name('com.pagico.clienty') != \
            dbus.bus.REQUEST_NAME_REPLY_PRIMARY_OWNER:
        method = session_bus.get_object('com.pagico.clienty',
                                        '/com/pagico/clienty')\
                                                .get_dbus_method("show_window")
        method()
        sys.exit(1)
    else:
        window = Pagico()
        client = PagicoClient(session_bus, window)
        client.run()
