<?php
$TPLCode["%TARGET_URL%"]=$GLOBALS["process_url"];
$TPLCode["%MESSAGE%"]=$GLOBALS["process_msg"];
$TPLCode["%ERROR_CAPTION%"]=$GLOBALS["ERROR_CAPTION"];
$TPLCode["%ERROR_MESSAGE%"]=$GLOBALS["Error_MSG"];
$TPLCode["%ONLINE_USER_DETECT_MODULE%"]=$GLOBALS["ONLINE_USER_DETECT_MODULE"];
?>